version: "3.9"

services:
  backend:
    image: cloudcrafterstack/course-api:latest
    container_name: crud-backend
    environment:
      - APP_CORS_ORIGINS=${APP_CORS_ORIGINS}
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: cloudcrafterstack/course-web:latest
    container_name: crud-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always



